apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app: laravel-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: php-container
          image: laravel-build-1:latest
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 9000
          volumeMounts:
            - name: www
              mountPath: /var/www
          env:
           - name: APP_NAME
             value: "Laravel"
           - name: APP_ENV
             value: "local"
           - name: APP_KEY
             value: "base64:vpEplxVGdB60hP/7jDP9Hqia1AQEtwDWdItXsvEgIsM"
           - name: APP_DEBUG
             value: "true"
           - name: APP_URL
             value: "http://localhost"

           - name: LOG_CHANNEL
             value: "stack"
           - name: LOG_DEPRECATIONS_CHANNEL
             value: "null"
           - name: LOG_LEVEL
             value: "debug"

           - name: DB_CONNECTION
             value: "mysql"
           - name: DB_HOST
             value: "mysql-service"
           - name: DB_PORT
             value: "3306"
           - name: DB_DATABASE
             value: "mysql_db_1"
           - name: DB_USERNAME
             value: "root"
           - name: DB_PASSWORD
             value: "MYSQL_ROOT_PASSWORD"

           - name: BROADCAST_DRIVER
             value: "log"
           - name: CACHE_DRIVER
             value: "file"
           - name: FILESYSTEM_DISK
             value: "local"
           - name: QUEUE_CONNECTION
             value: "sync"
           - name: SESSION_DRIVER
             value: "file"
           - name: SESSION_LIFETIME
             value: "120"

        - name: nginx-container
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /var/www
            - name: nginx-conf-2
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: app.conf
              readOnly: true
      volumes:
        - name: www
          emptyDir: {}
        - name: nginx-conf-2
          configMap:
            name: nginx-conf-2
            items:
              - key: app.conf
                path: app.conf
