apiVersion: v1
kind: Service
metadata:
  name: ngix-service
  labels:
    app: laravel-app
spec:
  ports:
    # this exposes ngix port to the outside world
    - port: 80
      protocol: TCP
  selector:
    app: app-pod
  type: NodePort
